repo: https://www.openssl.org/source/openssl-1.1.1m.tar.gz
ver: 1.1.1m
tag_prefix: openssl-
tag_dot2ul: false
cb_tool: perl
config_options_unix: no-tests no-comp no-async no-shared
config_options_embed: no-dso no-engine no-hw
config_options_msw: no-tests no-comp
