repo: https://github.com/openssl/openssl.git
ver: 1.1.1m
tag_prefix: OpenSSL_
tag_dot2ul: true
cb_tool: perl
config_options_1: no-shared no-threads no-async no-unit-test
config_options_2: no-dso no-hw no-engine
config_options_msw: no-unit-test
