#
# Copyright (c) 2021-2022 Bytedance Inc. @2022_1
#

name: build-ci

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events
  push:
    paths:
      - .github/workflows/build-ci.yml
      - 1k/build*
      - 1k/ios.mini.cmake
      - src/**/*
      - toolchain.properties
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      no_dll:
         # actions run ID
         description: 'Do not build windows lib as dll'
         # Default value if no value is explicitly provided
         default: ''
         # Input has to be provided for the workflow to run
         required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  linux:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    env:
      BUILD_TARGET: linux
      BUILD_ARCH: x64

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build
        run: source 1k/build.sh $BUILD_TARGET $BUILD_ARCH

      - name: Upload prebuilt files
        uses: actions/upload-artifact@v2
        with:
          path: ./${{ env.INSTALL_ROOT }}/**
          name: ${{ env.INSTALL_ROOT }}

  osx:
    # The type of runner that the job will run on
    runs-on: macos-10.15
    
    env:
      BUILD_TARGET: osx
      BUILD_ARCH: x64

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build
        run: ./1k/build.sh $BUILD_TARGET $BUILD_ARCH

      - name: Upload prebuilt files
        uses: actions/upload-artifact@v2
        with:
          path: ./${{ env.INSTALL_ROOT }}/**
          name: ${{ env.INSTALL_ROOT }}

  ios:
    # The type of runner that the job will run on
    runs-on: macos-10.15
    
    strategy:
      matrix:
        arch:
          - arm
          - arm64
          - x64
    
    env:
      BUILD_TARGET: ios
      BUILD_ARCH: ${{ matrix.arch }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.3.0
        with: 
          xcode-version: '12.4'

      - name: Build
        run: ./1k/build.sh $BUILD_TARGET $BUILD_ARCH

      - name: Upload prebuilt files
        uses: actions/upload-artifact@v2
        with:
          path: ./${{ env.INSTALL_ROOT }}/**
          name: ${{ env.INSTALL_ROOT }}

  android:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        arch:
          - arm
          - arm64
          - x86
    
    env:
      BUILD_TARGET: android
      BUILD_ARCH: ${{ matrix.arch }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build
        run: source 1k/build.sh $BUILD_TARGET $BUILD_ARCH

      - name: Upload prebuilt files
        uses: actions/upload-artifact@v2
        with:
          path: ./${{ env.INSTALL_ROOT }}/**
          name: ${{ env.INSTALL_ROOT }}

  windows:
    # The type of runner that the job will run on
    runs-on: windows-2019
    
    # Run a job for each of the specified target architectures:
    strategy:
      matrix:
        arch:
          - x86
          - x64
    env:
      BUILD_TARGET: windows
      NO_DLL: ${{ github.event.inputs.no_dll }}
      BUILD_ARCH: ${{ matrix.arch }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: ilammy/msvc-dev-cmd@v1.10.0
        with:
          arch: ${{ env.BUILD_ARCH }}

      - name: Build
        run: .\1k\build.ps1 $env:BUILD_TARGET $env:BUILD_ARCH

      - name: Upload prebuilt files
        uses: actions/upload-artifact@v2
        with:
          path: ./${{ env.INSTALL_ROOT }}/**
          name: ${{ env.INSTALL_ROOT }}
